
default: &default
  adapter: sqlite3


development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:

        adapter: postgresql
        encoding: unicode
        url: <%= ENV['DATABASE_URL'] %>

